Kava-Labs/oros

src/assets/orosLogo256.svg
=> feat: add smaller oros logo

src/App.tsx
this ensures that old toolcalls that arent resolved are cleaned up between requests
=> feat: reset toolcallStreamStore between requests

src/App.tsx, src/ChatView.test.tsx, src/ChatView.tsx, src/config/prompts/systemPrompt.ts, src/stories/ChatView.stories.ts, src/types.ts
=> feat: custom caution text for kava webapp integration

src/toolCallStreamStore.test.ts
=> test: verify error paths in toolCallStreamStore

src/App.tsx, src/AppContext.tsx, src/ChatView.test.tsx, src/ChatView.tsx, src/Conversation.tsx, src/main.tsx, src/stories/ChatView.stories.tsx
- For comparison purposes - moves display-driven state values from App ➡️  to Context.
- Reduces the need for prop drilling
=> poc: lightweight context

src/components/Conversation.tsx, src/components/ToolCallProgressCards.tsx, src/types/chain.ts
=> Optional Custom component that renders as the tool call argument stream is in progress

src/App.tsx, src/context/AppContext.tsx, src/context/AppContextProvider.tsx, src/context/wallets/metamask.ts, src/services/chain/registry.ts, src/types/chain.ts
=> feat: executeOperations / run the tool call

src/App.tsx, src/config/index.ts, src/context/AppContextProvider.tsx, src/services/chain/messages/cosmos/base.ts, src/services/chain/messages/cosmos/msgSend.ts, src/services/chain/messages/evm/base.ts, src/services/chain/messages/evm/transfer.ts, src/services/chain/messages/kava/lend/msgDeposit.ts, src/services/chain/registry.ts, src/stories/ChatView.stories.tsx, src/utils/chat/helpers.ts
=> feat: eth send with updated architecture

src/services/chain/messages/cosmos/base.ts, src/services/chain/messages/evm/base.ts, src/services/chain/queries/evm/base.ts, src/services/chain/registry.ts, src/types/chain.ts
=> refactor: enums for operation & chain type

src/services/chain/queries/evm/evmBalances.ts
=> fix: unmask address in balances query

src/services/chain/messages/evm/transfer.ts
=> fix: up default hard-coded gas for eth transfers

src/services/chain/messages/evm/transfer.ts, src/services/chain/messages/kava/lend/msgDeposit.ts, src/services/chain/queries/evm/evmBalances.ts, src/types/chain.ts
=> feat: wallet validation

src/components/QueryInProgress.tsx, src/services/chain/queries/evm/evmBalances.ts
=> feat: query in progress component

src/App.tsx, src/config/evm.ts, src/config/prompts/defaultPrompts.ts, src/services/chain/messages/evm/transfer.ts, src/services/chain/queries/evm/evmBalances.ts
=> fix: update token symbols

src/App.tsx, src/context/AppContextProvider.tsx, src/services/chain/messages/evm/transfer.ts, src/services/chain/messages/kava/lend/msgDeposit.ts, src/services/chain/queries/evm/evmBalances.ts, src/types/chain.ts
=> feat: attempt to connect to a wallet when operation wants wallet connect

src/App.tsx, src/components/Conversation.tsx, src/types/chain.ts
=> feat: only show CompleteTxDisplay on tx success

e2e/fixtures/index.ts
=> refactor: remove unused test fixture

src/services/chain/messages/evm/transfer.ts
=> feat: fix native send

src/components/CompleteTxDisplay.tsx, src/components/Conversation.tsx, src/components/InProgressTxDisplay.tsx, src/components/QueryInProgress.tsx, src/components/ToolCallProgressCards.tsx, src/types/chain.ts, src/useScrollToBottom.tsx
=> feat: scroll to bottom of container for inProgress/tx complete cards

src/textStreamStore.ts
=> feat: textStreamStore only emitChange when state changes

.github/workflows/ci-cd.yml
=> ci: include e2e secrets in ci-cd.yml

e2e/chat.spec.ts, src/config/chainsRegistry.ts
- Adds e2e test for transferring USDt on internal testnet
- Adjusts enum values for better display
=> test: verify non-native erc20 test via playwright

src/App.tsx
=> feat: fix JSON.stringify on instanceof Error

src/config/prompts/defaultPrompts.ts
https://github.com/user-attachments/assets/4325e8d1-3f47-493f-a18b-43c041a292a7
=> fix: adjust system prompt to remove repetitive information in balance query

src/App.tsx
=> fix: remove logs

e2e/chat.spec.ts, src/components/displayCards/CompleteQueryDisplay.tsx
=> fix: adjust playwright selectors for balances query

e2e/chat.spec.ts, src/config/prompts/defaultPrompts.ts
https://github.com/user-attachments/assets/dab157a9-c6ad-4a99-a528-d6f78733abf5
=> feat: tx is confirmed in wallet, not chat

src/components/displayCards/DisplayCards.module.css, src/components/displayCards/InProgressTxDisplay.tsx
Position the in-progress and tx display components for better alignment.
https://github.com/user-attachments/assets/f726ba7b-08df-4c04-998f-e74d66f5c3b0
=> style: transaction progress card positioning

src/context/AppContextProvider.tsx, src/context/types.ts, src/context/useExecuteOperation.tsx, src/services/modelRegistry.ts
=> feat: context code clean up and adding setModel function

src/core/types/models.ts, src/features/reasoning/config/models.ts, src/features/reasoning/config/prompts/defaultPrompts.ts, src/services/modelRegistry.ts
=> feat: move out reasoning config to it's proper feature dir

src/core/components/ChatView.tsx, src/core/components/NavBar.tsx, src/core/utils/isInIframe.ts
=> refactor: reusable helper for isInIframe

src/App.module.css, src/App.tsx, src/core/components/ChatHistory.module.css, src/core/components/ChatHistory.tsx
=> feat: chat history sidebar

src/App.tsx, src/core/config/models.ts, src/core/context/AppContextProvider.tsx, src/core/context/types.ts, src/core/types/models.ts
=> fix: refactor model configuration in app context

src/App.tsx, src/core/context/AppContextProvider.tsx, src/core/context/types.ts
=> feat: expose openAI client from app context

e2e/Chat.ts, e2e/chat.spec.ts, src/core/config/models.ts
As per mocks, deepseek is the default model. Also, its the only one supported on mobile.
=> feat: deepseek is the default model

src/core/components/ChatHistory.tsx, src/core/context/AppContextProvider.tsx, src/core/context/useMessageSaver.tsx
https://github.com/user-attachments/assets/06787429-a28e-4097-b67f-d354b9bab605
=> feat: generate title for conversation

src/core/config/models.ts
=> fix: tuck deepseek behind feature flag

e2e/chat.spec.ts, src/core/components/ChatView.module.css, src/core/components/ChatView.tsx, src/core/types/models.ts, src/features/blockchain/config/models.ts, src/features/blockchain/config/prompts/defaultPrompts.ts, src/features/blockchain/services/registry.ts, src/features/reasoning/config/models.ts, src/features/reasoning/config/prompts/defaultPrompts.ts
https://github.com/user-attachments/assets/b42e64ec-fec4-407e-a360-1d6128c76557
=> style: input placement with slide animation

src/App.tsx, src/core/components/NavBar.tsx
- hide the model selector when history is open per the figma
=> feat: hide model selector when history nav open

src/core/components/ChatHistory.tsx
=> feat: truncate longer chat history titles

src/core/components/ChatView.module.css
https://github.com/user-attachments/assets/39f4c86a-8978-4f8d-b2d4-dc52b3acaa75
=> style: input stays below chat with long conversation

e2e/chat.spec.ts, src/core/components/ChatHistory.tsx
=> test: chat history e2e workflows

src/core/components/ChatHistory.tsx, src/core/components/NavBar.tsx
=> fix: reset chat

src/core/context/AppContextProvider.tsx, src/core/context/types.ts, src/core/context/useMessageSaver.tsx
=> feat: fix chat history model switching

src/core/context/AppContextProvider.tsx
=> feat: reset error state and progress store on convo load

src/core/components/ChatHistory.tsx
=> fix conversation delete

.github/workflows/deploy-api-manual.yml
Manually trigger API deployment with commit hash
=> ci: Add manual api deployment workflow

src/App.tsx, src/core/assets/CancelChatIcon.tsx, src/core/components/ChatHistory.tsx, src/core/components/ChatView.tsx, src/core/components/NavBar.tsx
=> feat: subtle chat bug fixes

src/core/config/models.ts, src/features/reasoning/config/models.ts
=> feat: use correct deepseek id

src/core/components/ChatHistory.module.css
- Added hover styling to new chat button and history entries
- Also added some horizontal padding and border roundness for consistency
https://github.com/user-attachments/assets/ca2eb172-506a-4f88-b4b6-a0e90051d424
=> style: hover styles for history items and new chat

src/core/components/NavBar.module.css
- add pointer cursor for hamburger dropdown
=> style: pointer cursor

src/core/context/AppContextProvider.tsx
=> fix: reset system prompt on model change

src/core/components/ChatView.module.css
=> style: move start container up on mobile

src/core/components/ChatView.module.css
https://github.com/user-attachments/assets/8bb280fb-e01d-469c-9bc0-0dfd5ae6c8e1
=> style: remove logo on short screens (phones turned sideways)

src/core/components/ChatView.module.css
=> revert: mobile positioning which breaks iFrame integration

src/features/blockchain/components/displayCards/DisplayCards.module.css
=> fix: design polish v1

src/core/components/ChatView.module.css
=> revert: short positioning which breaks iFrame integration

e2e/chat.spec.ts, src/features/reasoning/config/models.ts
=> feat: rename and icon reasoning model

src/App.tsx, src/core/context/AppContextProvider.tsx
=> feat: if in iframe default model to blockchain

src/core/components/ModelDropdownExpanded.test.tsx
=> feat: add some tests coverage on model dropdown

.github/workflows/ci-cd.yml
=> feat: enable new Kava AI in production

src/core/components/ChatView.module.css, src/core/components/ChatView.tsx, src/core/components/Conversation.tsx
=> feat: show reset chat in prod and apply go-live

src/core/components/ChatView.module.css
=> style: avoid logo input collision on safari mobile

e2e/Chat.ts, e2e/chat.spec.ts
- test coverage for switching between conversations and verifying that local storage populates
=> test: chat history e2e coverage

src/core/components/NavBar.module.css
https://github.com/user-attachments/assets/146bfcbb-b492-499d-a910-c334494ac833
=> style: disabled styling for model selector

src/core/components/ChatView.tsx
Address #287 
https://github.com/user-attachments/assets/7c2bac56-f248-4fe3-bd47-d419ff159eda
=> style: resize input after submission

src/core/components/ChatView.module.css
=> style: don't wrap long markdown inputs

e2e/chat.spec.ts, src/features/blockchain/config/prompts/defaultPrompts.ts
=> feat: adjust blockchain instruct intro text

src/core/components/ChatHistory.tsx, src/core/components/ChatView.module.css, src/core/components/Conversation.tsx
https://github.com/user-attachments/assets/9379329c-47e6-4382-afa9-5aa58cc95cff
=> feat: make assistant responses copyable

e2e/chat.spec.ts, src/core/components/ChatHistory.tsx, src/core/components/NavBar.tsx
=> feat: reset isRequestingState back to false on new chat

e2e/chat.spec.ts, src/core/components/ChatHistory.tsx
=> feat: lint fixes

src/core/components/ChatHistory.module.css, src/core/components/ChatHistory.tsx
=> style: remove history border bottom

src/core/components/ChatHistory.module.css, src/core/components/ChatHistory.tsx
=> style: fix new chat button alignment between text and icon

src/core/components/ChatHistory.tsx
=> fix: always render map item with key

package-lock.json, package.json, src/core/context/useMessageSaver.test.ts, src/core/context/useMessageSaver.tsx
=> fix: only update lastSaved if history is edited

src/App.tsx, src/core/components/AssistantMessage.tsx, src/core/components/ChatView.test.tsx, src/core/components/ChatView.tsx, src/core/components/Content.tsx, src/core/components/Conversation.tsx, src/core/components/ThinkingContent.tsx, src/core/context/AppContextProvider.tsx, src/core/context/types.ts, src/core/stores/messageHistoryStore.ts, src/core/stores/stores.ts, src/main.tsx, src/stories/ChatView.stories.tsx
=> feat: reasoning Content separation 

src/App.tsx, src/core/components/ChatHistory.module.css, src/core/components/ChatHistory.tsx, src/core/components/ChatView.module.css, src/core/components/ChatView.tsx, src/core/components/NavBar.module.css
https://github.com/user-attachments/assets/418d0a1d-04ed-4cfd-9026-1bdd1ee68268
=> style: remove top nav from desktop design

e2e/chat.spec.ts, src/core/components/ChatView.module.css, src/core/components/ModelDropdownExpanded.test.tsx, src/core/components/ModelDropdownExpanded.tsx, src/core/components/ModelSelector.tsx, src/core/components/NavBar.module.css, src/features/blockchain/services/evm/evmBalances.ts, src/features/blockchain/services/messages/evm/transfer.ts
=> feat: enable blockchain model on mobile

src/core/components/ChatHistory.module.css, src/core/components/ChatHistory.tsx
=> feat: implement title editing

src/core/components/ChatHistory.tsx
=> fix: fix truncate title memo for editing

src/core/assets/TrashIcon.tsx, src/core/components/ChatHistory.module.css, src/core/components/ChatHistory.tsx, src/core/components/NavBar.module.css
https://github.com/user-attachments/assets/16ed6212-4c1e-408b-bec3-c96dc218e8e8
=> style: hover treatment for delete and edit icons

src/core/components/ChatHistory.tsx, src/core/components/NavBar.tsx
=> fix: reset thinking store on new Chat

src/core/components/ChatHistory.module.css, src/core/components/ChatView.module.css
=> style: add fade add top of chat

src/core/components/ChatView.module.css
=> fix: revert fade

src/core/components/ChatView.module.css
=> fix: scroll content not full visible in iframe

src/core/config/models.ts, src/core/context/AppContextProvider.tsx
https://github.com/user-attachments/assets/d9b4088c-77aa-41f2-8d19-7a4bd5203bb6
=> feat: default model selection through query params

src/App.tsx, src/core/context/AppContextProvider.tsx, src/core/context/types.ts
move all handlers and api calls to context
this is in prep for concurrent conversation support
=> refactor: clean up App.tsx move handlers to context 

src/core/components/ChatView.module.css
=> feat: fix mardown table rendering

.storybook/preview.ts, src/stories/ChatView.stories.tsx, src/stories/mockdata.ts
https://github.com/user-attachments/assets/78cf449c-676b-44f5-851f-3fe582e1a345
=> feat: add markdown Rendering Test to storybook

src/core/components/ChatView.module.css, src/core/components/Content.module.css, src/core/components/Content.tsx, src/main.tsx, src/shared/theme/global.css
=> feat: isolate content styles

src/core/components/ChatHistory.module.css
=> fix: use secondary text color for menu buttons

e2e/chat.spec.ts, src/core/components/ChatHistory.tsx
Confirms the bug @samcode206 found as part of #375 and adds e2e test to verify a fix
=> fix: title edit 🐛 

playwrightInit.bash
=> ci: reintroduce health check before playwright

src/App.tsx, src/core/components/ChatHistory.tsx, src/core/context/AppContextProvider.tsx, src/core/utils/sanitize.test.ts
=> fix: lints and dependencies, and unused vars/imports

api/cmd/api/middleware/http_metrics.go
Adds model name to http request labels. 
ex:
```
http_requests_total{code="200",handler="/chat/completions",method="post",model="deepseek-r1"} 1
http_requests_total{code="200",handler="/chat/completions",method="post",model="gpt-4o-mini"} 1
```
=> feat(api): Include model label in http metrics

e2e/chat.spec.ts, src/core/components/ChatHistory.tsx, src/core/context/AppContextProvider.tsx
=> feat: new chats start with a placeholder

src/core/types/models.ts, src/features/blockchain/config/models.ts, src/features/reasoning/config/models.ts
=> config: add `contextLength` property to model config

src/features/reasoning/config/models.ts
=> config: update reasoning model context length

src/core/context/AppContextProvider.tsx
=> Revert "fix: clear message history store before switching model"

e2e/Chat.ts, e2e/chat.spec.ts
=> test: update playwright message locator & history test

src/App.tsx, src/core/assets/SearchHistoryButton.tsx, src/core/components/ChatInput.tsx, src/core/components/ChatView.tsx, src/core/components/Conversation.tsx, src/core/components/LandingContent.tsx, src/stories/ChatView.stories.tsx
- removed unnecessary prop drilling in favor of context
- made a `LandingContent` component for before a conversation starts
=> refactor: `Chatview` cleanup

src/App.tsx, src/core/components/DesktopSideBar.tsx, src/core/components/MobileBackdrop.tsx, src/core/components/MobileSideBar.tsx
- App now returns components rather than some components JSX, so its easier to reason about purpose and structure.
=> refactor: componentize sidebars

index.html
Improvement on the current default
=> feat: add meta description for better search engine results

src/core/components/ChatInput.module.css, src/core/components/ChatInput.tsx
- use theme spacing 
-  move remove image icon to top left
- refactor button disabled conditional to be more readable
=> refactor: use theme elements

.github/workflows/ci-cd.yml, .github/workflows/playwright.yml, e2e/chat.spec.ts, playwrightInit.bash, src/core/components/ChatInput.module.css, src/core/components/ChatInput.tsx
- only allow the user to upload 4 files, both through icon and drag & drop
- alert the user if they attempt to go over the limit
- verify via e2e tests
https://github.com/user-attachments/assets/154a333e-e9fc-49c8-95d3-e519b6a085e6
=> feat: limit number of upload files

src/core/components/Conversation/Conversation.tsx
=> fix: remove duplicate aria label

src/core/components/Conversation/ThinkingContent.tsx
=> fix: remove duplicate identifier

src/core/components/Conversation/Conversation.tsx
=> Revert "fix: remove duplicate aria label"

playwrightInit.bash
=> fix: remove commented out

src/core/types/models.ts, src/features/blockchain/config/models.ts, src/features/reasoning/config/models.ts
- will be implemented once file upload PR is merged
=> config: add supported file types to model config

src/core/components/ChatInput.tsx, src/core/components/Conversation/Conversation.test.tsx, src/core/components/Conversation/Conversation.tsx
https://github.com/user-attachments/assets/0895f741-fbb9-4bf8-a335-7fe311fb746e
=> feat: no drag & drop or icon on blockchain model

.github/workflows/ci-cd.yml
=> ci: feature flag

src/core/context/utils.ts
=> remove console log from analyzeImage

src/core/components/ChatInput.module.css
=> style: center attach icon

src/core/components/Conversation/Conversation.module.css, src/core/context/utils.ts
- fix CSS nesting so ellipses animation returns for progress text
https://github.com/user-attachments/assets/1bf49bcf-949c-4389-9760-ade76aa1b139
https://github.com/user-attachments/assets/9c1f7f76-85c9-4c19-8d76-117429a5e3ff
=> style: progress animation 

src/core/components/ChatInput.tsx
- always enabled during requesting so a user can cancel
-
=> fix: cancel button state

api/cmd/api/main.go
Prevent any parent router match from producing metrics with the path, produces high-cardinality labels
=> fix(api): Limit metrics middleware to matched routes

.github/workflows/ci-cd.yml
=> feat: flip feature flag for file uploads

api/internal/handlers/openai.go, api/internal/types/client.go
- Add backend and model labels to proxy client metrics
- Track client request duration, size, etc.
=> feat(api): Add backend and model to proxy client metrics

.github/workflows/ci-cd.yml, .github/workflows/playwright.yml, src/core/components/ChatInput.tsx
=> config: remove deprecated feature flag

src/core/components/ChatInput.tsx, src/core/hooks/useDragAndDrop.test.ts, src/core/hooks/useHandleDragAndDrop.ts
- extract drag and drop behavior to a hook
- verify via unit tests
=> refactor: drag and drop

src/core/components/ChatInput.tsx, src/core/hooks/useDragAndDrop.test.ts, src/core/hooks/useDragAndDrop.ts, src/core/types/models.ts, src/features/blockchain/config/models.ts, src/features/reasoning/config/models.ts
Similar to #462 , but for maximum file uploads allowed
=> refactor: maximum files moved to model config

src/core/components/ChatInput.tsx, src/core/hooks/useDragAndDrop.test.ts, src/core/hooks/useDragAndDrop.ts, src/core/types/models.ts, src/features/blockchain/config/models.ts, src/features/reasoning/config/models.ts
=> refactor: move maximum file bytes to model config

src/core/config/models.ts, src/core/context/utils.ts
- this will lay the ground work for rendering thinking content for Qwen when it is added to the registry of reasoning models
=> refactor: extensible rendering of thinking content

src/core/config/models.ts, src/core/context/utils.ts, src/core/types/models.ts, src/features/reasoning/config/models.ts
=> refactor: string literals for model names

src/core/components/ChatInput.tsx, src/core/hooks/useDragAndDrop.test.ts, src/core/hooks/useDragAndDrop.ts
=> refactor: pass modelConfig to useDragAndDrop

src/core/components/ChatInput.tsx
=> fix: run linter

src/core/components/ChatInput.tsx, src/core/hooks/useDragAndDrop.test.ts, src/core/hooks/useDragAndDrop.ts, src/core/hooks/useProcessUploadedFile.test.ts, src/core/hooks/useProcessUploadedFile.ts
=> refactor: process upload file hook

.github/workflows/ci-cd.yml, .github/workflows/playwright.yml, e2e/chat.spec.ts, src/core/config/models.ts, src/core/context/utils.ts, src/core/types/models.ts, src/core/utils/streamUtils.ts, src/features/blockchain/config/models.ts, src/features/reasoning/config/models.ts, src/features/reasoning/helpers.ts
=> Revert "feat: qwen model behind feature flag"

.github/workflows/ci-cd.yml, .github/workflows/playwright.yml, e2e/chat.spec.ts, src/core/config/models.ts, src/core/context/utils.ts, src/core/types/models.ts, src/core/utils/streamUtils.ts, src/features/blockchain/config/models.ts, src/features/reasoning/config/models.ts, src/features/reasoning/helpers.ts
=> Restore: qwen model behind feature flag

e2e/chat.spec.ts, src/core/components/Conversation/Conversation.tsx, src/core/components/Conversation/ImageCarousel.module.css, src/core/components/Conversation/ImageCarousel.tsx
=> style: use theme elements for pdf preview

e2e/chat.spec.ts, src/core/components/Conversation/Conversation.tsx, src/core/components/Conversation/ImageCarousel.tsx
=> test: fix playwright

src/core/components/LandingContent.tsx, src/core/utils/pdf.ts
=> fix: pdf text extraction EOL

src/core/components/Conversation/ImageCarousel.tsx
for up to 12 images, otherwise hide the dots
=> feat: conditionally render image carousal dots

src/core/components/ChatInput.tsx, src/core/hooks/useAvailableUploads.test.ts, src/core/hooks/useAvailableUploads.ts
- use hook to DRY out repetitive error states
=> refactor: implement useUploadingError

src/core/components/Conversation/AssistantMessage.tsx, src/core/components/Conversation/Conversation.module.css, src/core/components/Conversation/ErrorMessage.test.tsx, src/core/components/Conversation/ErrorMessage.tsx, src/core/components/Conversation/StreamingMessage.tsx
=> feat: remove kava icon from assistant messages

src/core/components/ChatInput.tsx
=> fix: adjust aria label for cta button based on isRequesting state

e2e/chat.spec.ts, src/core/components/ModelSelector.test.tsx, src/core/components/ModelSelector.tsx, src/core/config/models.ts, src/features/blockchain/config/models.ts
=> feat: remove blockchain instruct from list of models

src/core/components/SearchChatHistory.module.css
=> style: use contrasting bg color on hover

src/core/components/Conversation/Conversation.module.css, src/core/components/Conversation/StreamingText.test.tsx
The brain and the progress text both pulse
https://github.com/user-attachments/assets/7d1dbd4a-9396-4ad2-90ae-6e8906efdbf2
=> style: pulsing progress text

src/core/config/models/models.ts, src/core/context/utils.ts, src/core/types/models.ts, src/core/utils/conversation/hasSufficientRemainingTokens.ts, src/core/utils/conversation/helpers.test.ts, src/core/utils/conversation/helpers.ts
=> feat: use o3-mini as the default reasoning model

src/core/context/AppContextProvider.tsx, src/core/types/models.ts
=> feat: skip loading conversations with unsupported models

docker-compose.yaml
=> ci: allow qwen in build

src/App.tsx, src/core/components/ChatInput.test.tsx, src/core/components/ChatInput.tsx, src/core/components/ChatView.tsx, src/stories/ChatView.stories.tsx
=> refactor: lift up supports upload

src/App.tsx, src/core/components/ChatInput.test.tsx, src/core/components/ChatInput.tsx, src/core/components/ChatView.tsx, src/core/components/Conversation/AssistantMessage.test.tsx, src/core/components/Conversation/AssistantMessage.tsx, src/core/components/Conversation/AssistantStream.tsx, src/core/components/Conversation/Content.test.tsx, src/core/components/Conversation/Content.tsx, src/core/components/Conversation/Conversation.test.tsx, src/core/components/Conversation/Conversation.tsx, src/core/components/Conversation/ErrorMessage.test.tsx, src/core/components/Conversation/ErrorMessage.tsx, src/core/components/Conversation/MessageStream.tsx, src/core/components/Conversation/StreamingMessage.tsx, src/core/components/Conversation/StreamingText.test.tsx, src/core/components/Conversation/StreamingText.tsx, src/core/components/Conversation/StreamingTextContent.tsx, src/core/components/Conversation/ThinkingStream.tsx, src/core/components/LandingContent.tsx, src/stories/ChatView.stories.tsx
=> refactor: lift up modelConfig

src/App.tsx, src/core/assets/SearchHistoryButton.tsx, src/core/components/ChatHistory.tsx, src/core/components/DesktopSideBar.tsx, src/core/components/MobileSideBar.tsx, src/core/components/SearchHistoryModal.tsx, src/core/context/AppContextProvider.tsx, src/core/context/types.ts
=> refactor: lift up conversations and remove deprecated helper

src/core/components/SearchHistoryModalBody.tsx
The selected style here is handled with css on hover.
=> refactor: remove unneeded prop & style

src/App.tsx, src/core/components/Conversation/AssistantMessage.test.tsx, src/core/components/Conversation/AssistantMessage.tsx, src/core/components/ModelSelector.test.tsx, src/core/components/NavBar.test.tsx, src/core/components/NavBar.tsx, src/core/components/SearchHistoryModalBody.tsx, src/shared/theme/useIsMobile.tsx, src/shared/theme/useIsMobileLayout.tsx
First step toward importing the utility from lib
=> refactor: rename useIsMobile to reference layout (not device)

src/useSession.tsx
=> fix: use application/json for session requets

src/App.tsx, src/core/components/ChatInput.test.tsx, src/core/components/ChatInput.tsx, src/core/components/ChatView.tsx, src/core/components/Conversation/Conversation.test.tsx, src/core/components/Conversation/Conversation.tsx, src/stories/ChatView.stories.tsx
=> refactor: lift context values from chat input

package-lock.json, src/App.module.css, src/App.tsx
=> feat: link to oros blockchain app

src/App.module.css
=> feat: fix link spacing

api/internal/handlers/openai.go
Prevent 500 responses and error span statuses when http request context is cancelled
=> fix: Ignore request ctx cancel errors

src/App.module.css, src/core/components/NavBar.module.css
=> style: match nav bar padding between projects

src/App.module.css
=> style: project link arrow shows on hover only

package-lock.json
=> fix: update lib version

api/internal/handlers/openai.go
Investigating vLLM backend Invalid Requests
=> feat: Additional proxied request logging

api/internal/handlers/openai.go, api/internal/types/client.go
Issue has been resolved via https://github.com/Kava-Labs/oros/pull/539
=> chore: Remove request dump, excess logging

src/core/config/models/defaultPrompts.ts
=> fix: include name in system prompt
