- src/ChatView.module.css
After reviewing other products in the AI landscape, others still align left for user message that overflow past a single line.
> style: revert align right for long user messages

- src/ChatView.module.css
- src/Content.tsx
- src/sanitize.test.ts
- src/utils/chat/helpers.test.ts
- src/utils/chat/helpers.ts
Reimplements #142 but without breaking apart markdown links (like the hash link returned from a successful tx)
> feat: no horizontal scroll, but don't break apart markdown links

- src/stories/ChatView.stories.tsx
- makes storybook work again now that we have a Theme
> fix: wrap story in theme provider

- src/App.tsx
- src/ChatView.tsx
Removes two explicit error checks
> fix: clean up two explicit errors handled elsewhere

- src/components/ChatView.module.css
Make both assistant and user classes max width 80% so they break to the next line instead of creating horizontal scroll
https://github.com/user-attachments/assets/82b46d1b-4451-4cc7-a3f5-ed77a29085e7
https://github.com/user-attachments/assets/3e23dbaf-e02a-45d2-8636-2841a7e1b0cd
> style: prevent horizontal scroll for assistant messages

- src/config/chainsRegistry.ts
- src/config/prompts/defaultPrompts.ts
Addresses Issue #194 
- added examples of transacting with other chains
- made the chain name a part of all tx details 
Example issue
User: Send 1 USDT to ...
Assistant: Can you please specify which chain?
https://github.com/user-attachments/assets/1365699e-6bbe-4435-a2cb-d1642a9ca018
> feat: add chain name to tx confirmation details

- src/context/AppContextProvider.tsx
- src/services/chain/messages/evm/transfer.ts
- src/types/chain.ts
- adds a private method to EvmTransferMessage for validating that a user has enough of a particular denom (on a particular chain) 
- calls this message as part of the validation check
https://github.com/user-attachments/assets/d9b02f98-ffb7-4af7-9563-cdc3db99a15b
https://github.com/user-attachments/assets/dd19b92e-36b1-4ab7-b646-1a6005e0304d
- After this, we should refactor the `inProgressComponent` to only render if the `validate` method succeeds. Right now, it shows that the tx is in progress, but then the validation fails and it goes away
> fix: validate users balances before transfer

- e2e/chat.spec.ts
- src/components/ConnectWalletPrompt.tsx
- src/components/InProgressTxDisplay.tsx
- src/context/AppContext.tsx
- src/context/AppContextProvider.tsx
- src/services/chain/messages/evm/transfer.ts
- src/useScrollToBottom.tsx
Addresses Issue #203 
https://github.com/user-attachments/assets/b14488fd-68cb-4de8-a2c1-9dc1ac69be34
https://github.com/user-attachments/assets/5d6ff118-88f1-4c86-9619-b88f41fe9af4
- It would be nice to not render the empty assistant message that's above the in progress card, causing it to not be aligned with the icon
- For the error path, we see "Thinking" ➡️  "{{empty}}" ➡️ "Thinking" ➡️ "{{error text}}" and it would be nice to eliminate those middle two states
> fix: don't show in progress until validation passes

- src/config/prompts/defaultPrompts.ts
A few times, when I asked "What are my balances" I got a response of "What chain do you want to check?" so the model wasn't quite clear on the concept of a default if not specified.
Also, I adjusted our examples to include clearer examples. If you ask for your USDt balance on Kava, we currently return all of your balances, not just the specified one.
Got it right 4/4
https://github.com/user-attachments/assets/6a70988b-3ce5-47e6-ac3b-0af34980bf28
> fix: harden prompt for chain balances query

- src/services/chain/queries/evm/evmBalances.ts
If there's an error fetching contract balances (occurring because we have a hardcoded list that don't exist in all env's), log the error to the console, but don't display the error in the UI, simply skip and move on.
> fix: don't display asset if balance fetching failed

- src/components/displayCards/DisplayCards.module.css
- Fixes some spacing issues when balances are long by lowering the font-size a bit for the amount
- Adjusts the denom font size since it now looks out of place with the smaller amount font size
- adjusts some of the spacing in the cards to make sure items are centered and with less padding
> feat: cleanup balances display card styles

- e2e/Metamask.ts
- e2e/chat.spec.ts
- e2e/fixtures/index.ts
Metamask-related test can be flaky since we are relying on different pop ups. Retrying button clicks seems to work for certain stages of the process, so let's propagate that to all button clicks within the metamask workflow.
> ci: implement button click retries in metamask workflow

- .github/workflows/ci-cd.yml
- .github/workflows/playwright.yml
- e2e/chat.spec.ts
- src/App.tsx
- src/core/components/ModelDropdownButton.tsx
- src/core/components/ModelDropdownExpanded.tsx
- src/core/components/ModelSelector.tsx
- src/core/components/NavBar.module.css
- src/core/components/NavBar.tsx
- src/core/config/models.ts
- src/core/context/AppContextProvider.tsx
- src/features/blockchain/components/displayCards/DisplayCards.module.css
- if a user clicks outside of the dropdown it closes
- a user can use the arrow keys to toggle options
- the user can use the enter and escape keys to manipulate the dropdown
- the dropdown is disabled if a user has started a chat, but becomes enabled again when history is cleared
https://github.com/user-attachments/assets/526a6c31-5b19-48ac-ad3a-94404f6d55da
> feat: handle disabled states for dropdown

- .github/workflows/ci-cd.yml
If playwright tests fail, encrypts playwright test results with the pull request / pusher's gpg key set in github
> ci: Upload encrypted playwright test results to artifacts on failure

- src/core/components/AssistantMessage.tsx
- src/core/components/ChatView.module.css
- src/core/components/Conversation.tsx
- Copy icon was aligned to the right, whereas industry-standard has it left aligned.
- Breaks AssistantMessage component into its own file
> style: align copy icon left

- src/core/components/ModelDropdownButton.tsx
- src/core/components/ModelDropdownExpanded.tsx
- src/core/components/NavBar.module.css
- src/core/components/Tooltip.module.css
- src/core/components/Tooltip.tsx
- creates a reusable, positionable tooltip component for handling the disabled state of the model selector dropdown (when a conversation has started) and for switching to a blockchain model on mobile
https://github.com/user-attachments/assets/1aafe8c7-7ae0-4321-98e0-793b0ef82acf
> feat: add tooltip for disabled states in model selection

- e2e/chat.spec.ts
In order for the delete icon to be located, we need to either hover over the conversation title, or click it and bring it into focus
> test: re-enable delete history e2e tests 

- src/core/components/ChatView.module.css
Sometimes the model will respond with markdown that will get converted into elements like <h3>. We need to apply custom styling in those cases to keep it looking nice.
Header elements get margin bottom from the global style.
But if its part of the assistant response, then we should give it equal margin top.
> style: alignment for assistant headers

- src/core/components/ChatView.tsx
Addresses #317 
Auto-scroll the chat as before, but if a user decides to scroll up, allow them to do so. 
If they scroll back to the bottom of the chat, resume auto-scroll
It only allowed me to scroll up briefly when the stream paused/slowed down
https://github.com/user-attachments/assets/2e9ba141-d53a-4d94-a615-040525edd99d
https://github.com/user-attachments/assets/1e836fb6-77a6-404c-9fcf-9557289f830d
> fix: allow users to scroll up when content is streaming

- e2e/chat.spec.ts
- src/core/components/ChatHistory.module.css
- src/core/components/ChatHistory.tsx
- src/core/components/ChatView.module.css
- Adds an input to search/filter conversation history by title match
- Moved the conversations state into a useState hook instead of reading directly from localStorage on every render
- Added useMemo for filtering and grouping conversations
- Memoized the HistoryItem component using React.memo
- Memoized the truncateTitle function and its result
https://github.com/user-attachments/assets/aa816cb7-fc56-4e70-abd9-f7a0fec07320
> feat: chat history search (title)

- src/core/components/ModelSelector.tsx
Clicking the current selection was firing both close on outside click, and _then_ toggling the state back to open.
Move the locator to the parent of the dropdown
https://github.com/user-attachments/assets/396fe816-6242-4d76-852c-0aae58629f43
https://github.com/user-attachments/assets/c9b6d0ba-03a7-41c9-9d00-26738818eb45
> fix: adjust click on outside close to encompass the entire dropdown

- src/core/components/ChatHistory.tsx
> fix: hide chat options tooltip

- index.html
Without the maximum-scale set, the edit history and search input on mobile will zoom in on click, but not zoom out after typing.  This change keeps the scale the same.
Tested on iphone 15 simulator and fixes the zoom behavior.
> fix: add max scale to prevent zoom on inputs

- src/core/components/ButtonIcon.module.css
This uses the hover media query to only enable hover states on devices that support it.  This fixes the undesried the sticky state on touch.
> fix: Remove sticky hover states and tooltips on touch devices

- .github/workflows/ci-cd.yml
Does a string match so having the `./` in front fails to match diff output
```bash
$ git diff '5706d4d404f71f671cbc4bcb733121f7e1a25891...85265cf6b46cbdbf39a4a7ef54e4bffa67d6d857' '--diff-filter=AMRC' --name-only
api/README.md
api/cmd/api/config/config.go
api/cmd/api/config/config_test.go
api/cmd/api/handlers/openai.go
api/cmd/api/handlers/openai_test.go
```
> fix(ci): Update get-diff-action api pattern

- e2e/chat.spec.ts
- src/core/components/ChatHistory.tsx
This is similar to the change recently made for title editing. If a user clicks to delete a chat, we don't want to wait for a synchronous action to complete before updating the UI.
We will track conversations in local state and remove it from there first and then schedule the update to local storage.
https://github.com/user-attachments/assets/5dbade08-8683-4c8d-8ec1-c695642843c7
https://github.com/user-attachments/assets/e66add22-5801-4331-b929-ea3c52c6ecf3
> fix: delete from UI, then from local storage

- src/core/context/AppContextProvider.tsx
Fixes a 🪲  where switching models after an active conversation was not correctly setting the new system prompt
Notice that its talking about Kava EVM on the reasoning model
https://github.com/user-attachments/assets/c0929867-5922-41cc-a1a5-47a5ad4f59b1
https://github.com/user-attachments/assets/62b36fad-8d6d-46e5-93b4-36dfb2a6ed3e
> fix: clear message history store before switching model

- e2e/Chat.ts
- src/core/context/AppContextProvider.tsx
Gets renamed to the placeholder 
https://github.com/user-attachments/assets/8cffdda6-ad28-4a78-bb9d-30825fed1e01
https://github.com/user-attachments/assets/1e18e77f-36c8-4a43-9922-833d43e10629
> fix: don't rename an existing conversation

- src/core/components/ChatInput.tsx
- src/core/components/InputAdornmentMessage.module.css
- src/core/components/InputAdornmentMessage.tsx
- src/core/hooks/useManageContextWarning.ts
- src/core/types/models.ts
- src/core/utils/conversation/helpers.test.ts
- src/core/utils/conversation/helpers.ts
- src/features/blockchain/config/models.ts
- src/features/reasoning/config/models.ts
- src/shared/theme/themes.ts
- when a user crosses a threshold of token usage for a conversation, the warning is shown
- the user can close the warning and it won't be shown again while that conversation remains in view
- if the user returns to that conversation later, the warning will be shown (we aren't storing that preference on the conversation history)
https://github.com/user-attachments/assets/dec4e6e3-0259-4cb9-9c32-797218c0269c
- Warning shown
- no close icon (just start new chat)
- send button disabled
> feat: show context limit warning UX (demo)

- api/README.md
- api/cmd/api/config/config.go
- api/cmd/api/handlers/files_download.go
- api/cmd/api/handlers/files_upload.go
- api/cmd/api/main.go
- aws/buckets.sh
- docker-compose.yaml
- Configurable path style S3 requests (for less issues with subdomains and networking on docker)
- Add docker compose env vars for localstack
> feat(api): Enable local docker compose testing

- src/core/types/models.ts
- src/core/utils/conversation/helpers.test.ts
- src/core/utils/conversation/helpers.ts
- src/features/reasoning/helpers.ts
We only need to store `tokensRemaining` on ChatHistory in local storage and can derive any other information from the model config. This removes these unused properties on the `ContextMetrics` type
> refactor: adjust `ContextMetrics` properties

- src/core/context/AppContextProvider.tsx
Fixes #402 
While we want to strip out reasoning content before posting back to the model, we need to create a copy of messages with the reasoning preserved to render to UI
https://github.com/user-attachments/assets/21067d70-33e7-476c-983a-99aba01f45d9
> fix: prior reasoning content should persist in the UI

- src/core/context/AppContextProvider.tsx
- src/core/context/types.ts
- check and reset message history with system prompt when model change
> fix: reset system prompt on model change

- src/core/components/ChatInput.tsx
- address #417 
- hide icon
- early return from useEffect that implements drag & drop handlers
https://github.com/user-attachments/assets/40343a97-5ca4-4f98-af9c-4f68a8387dee
> config: hide upload behind feature flag

- e2e/chat.spec.ts
- src/core/components/ChatInput.tsx
- inform user if they attempt to upload a file over the 8MB limit via click or drag & drop
- if a user attempts to upload multiple files, it will filter out those too large and include those within limits
- verify through e2e tests
> feat: don't allow uploads of larger than 8MB

- src/core/components/Conversation/Content.test.tsx
- wrapped tests checking Content.tsx component state changes in an async and waitFor
- added comments for testing clarity
- removed a test checking an obvious code path but intentionally throwing an error in console to avoid confusion
> fix: wrap Content async tests in wait for

- src/core/components/ChatInput.module.css
- src/core/components/ChatInput.tsx
This keeps the flex-end controls, but uses a wrapping container around only the button icons to keep them centered in a line with each other.
In addition, removes the margin in favor of gap.  When using flex to align items, gap is preferred to set spacing between elements.
Before:
After:
> fix: Use a wrapper to center icons in line with each other

- src/core/context/AppContextProvider.tsx
- addresses #438 
- reset the thinking store when the user cancels the stream
> fix: reset thinking store on cancel click

- src/core/components/Conversation/Conversation.module.css
- src/core/components/Conversation/Conversation.tsx
- addresses #447 
- add loading skeleton for images
- this removes flash caused by images loading after text
https://github.com/user-attachments/assets/0aa66c02-256a-4fe5-8c79-482fa8ac0e95
> feat: loading skeleton for images in chat

- src/core/components/ChatInput.tsx
- src/core/hooks/useDragAndDrop.test.ts
- src/core/hooks/useDragAndDrop.ts
- src/core/types/models.ts
- src/core/utils/isInIframe.ts
- implements the model config approach for supported file types set up in #430 
- removes deprecated/unused `isInIframe` helper
> refactor: supported file types to model config

- src/core/context/AppContextProvider.tsx
- In this bug fix #401 , we inadvertently removed setting the initial system prompt. Nothing triggered `ensureCorrectSystemPrompt` to run on initial load, only on model switch
https://github.com/user-attachments/assets/99789468-160e-435a-b5fc-dbf944a24414
https://github.com/user-attachments/assets/88daf86d-53c2-4ef6-9497-0185244bcc98
> fix: ensure that the initial system prompt is set

- api/cmd/api/cors_test.go
- api/internal/middleware/preflight.go
- New `x-stainless-timeout` header causes CORS policy to block requests
- Set `Access-Control-Allow-Headers` to wildcard value
> fix(api): Allow any header for preflight check

- src/core/components/ChatInput.tsx
- src/core/hooks/useUploadingError.ts
This sets up a new hook to manage setting and clearing the uploading error state. It also replaces two instances of such duplication (uploading too many files & uploading too big a single file). Follow on PR's can address other specific cases to allow for more focused testing.
https://github.com/user-attachments/assets/79d195c0-3bf5-44c5-8dee-df578510a684
> refactor: extract upload error

- src/core/components/Conversation/Conversation.module.css
- src/core/components/Conversation/ProgressIcon.tsx
- src/core/components/Conversation/ProgressStream.tsx
- src/core/components/Conversation/StreamingText.test.tsx
When a request is processing, add a pulsing brain icon beside "Thinking..." 
When the progress text clears, so does the icon
https://github.com/user-attachments/assets/ad59efce-8b66-4f18-aa7c-0ac8233c2a30
> feat: add brain icon for progress

- src/core/components/Conversation/Conversation.module.css
- src/core/components/Conversation/Conversation.tsx
- src/core/components/Conversation/ImageCarousel.tsx
- defines the parent component for image uploads as the height of the image upload so that it is blank until the image loads and doesn't shift text down
https://github.com/user-attachments/assets/e5b93785-de49-4beb-88fb-53f1129aa42f
- handles the loading state for carousel internally by hiding it until the first image is loaded (otherwise we just get a collapsed version)
https://github.com/user-attachments/assets/993b2fb8-8098-47bc-b50c-52366bf0172d
> fix: empty space equal to the image upload for single and multiple

- src/App.tsx
- src/core/components/ChatView.tsx
- src/core/components/ChatViewContainer.tsx
- src/core/components/Conversation/Conversation.test.tsx
- src/core/components/Conversation/Conversation.tsx
- src/core/components/ModelSelector.test.tsx
- src/core/components/ModelSelector.tsx
- src/core/components/NavBar.test.tsx
- src/core/components/NavBar.tsx
- src/core/context/useChat.tsx
- src/stories/ChatView.stories.tsx
Now that we've migrated off of context, we can continue the refactor of lifting state out of view components.
This first pass removes the chat view's subscription to the message history store and passes the message array instead of a store as props.
> refactor: containerize chat

- src/core/context/utils.ts
An empty array causes issues with o3-mini, causing looping responses and invalid outputs.  If no tools exist, it's better to leave the value as undefined.
> fix: Do not send empty tool array for completions

- api/internal/types/client.go
- docker-compose.yaml
"client" span types instead of "internal" produces inferred nodes in x-ray. Use events instead of subspans, so they don't produce additional nodes
> fix: Disable otelhttp subspans

- e2e/Chat.ts
- src/core/components/Conversation/Content.test.tsx
- src/useSession.test.tsx
- src/useSession.tsx
- remove the POST /session for heartbeat in favor of keepalive since it works on all requests and accomplishes the same thing
> feat: drop POST requests in favor of GET keepalive

- .github/workflows/ci-cd.yml
- .github/workflows/playwright.yml
- e2e/chat.spec.ts
- src/useSession.test.tsx
- src/useSession.tsx
- track impressions better from campaign driven events to the rails backend
- track `landing_page_url` and `referrer_url` on app load
- include them as query params to the backend session request
- after session request set, remove utm params from url
> feat: add impression information to session requests

- api/cmd/api/server_test.go
- api/internal/handlers/openai.go
- api/internal/types/client.go
Using `Transfer-Encoding: chunked` replicates "Invalid HTTP request received." response error from vLLM.
Using explicit Content-Length avoids chunked encoding.
http docs: https://pkg.go.dev/net/http#NewRequestWithContext
> If body is of type [*bytes.Buffer](https://pkg.go.dev/bytes#Buffer), [*bytes.Reader](https://pkg.go.dev/bytes#Reader), or [*strings.Reader](https://pkg.go.dev/strings#Reader), the returned request's ContentLength is set to its exact value (instead of -1), GetBody is populated (so 307 and 308 redirects can replay the body), and Body is set to [NoBody](https://pkg.go.dev/net/http#NoBody) if the ContentLength is 0.
> fix: Use explicit Content-Length header
